import React from "react";

export default function Footer() {
  return (
    <footer className="bg-gray-100 p-4 text-center text-sm text-gray-500">
      © 2024 Task Manager Pro — generated by Looma
    </footer>
  );
}
